---
abstract: 'A Bot::BasicBot::Pluggable Module to give out Gitweb links for commits.'
author:
  - 'Jacob Helwig <jhelwig@cpan.org>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bot-BasicBot-Pluggable-Module-Gitbot
requires:
  Bot::BasicBot::Pluggable: 0
  File::Basename: 0
  File::Fu: 0
  File::HomeDir: 0
  Git: 0
  MooseX::Declare: 0
  Text::Pluralize: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Bot-BasicBot-Pluggable-Module-Gitbot
  homepage: http://github.com/jhelwig/Bot-BasicBot-Pluggable-Module-Gitbot
  license: http://dev.perl.org/licenses/
  repository: git://github.com/jhelwig/Bot-BasicBot-Pluggable-Module-Gitbot.git
version: 0.01
